format = """
$directory$git_branch$git_status
$character"""

[directory]
style = "cyan"

[git_branch]
symbol = "ğŸŒ± "
style = "green"

[character]
success_symbol = "[â¯](bold green) "
error_symbol = "[â¯](bold red) "

